version: "3.9"

services:
  dashboard:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dashboard
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /app

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hackone-api
    ports:
      - "3001:3001"
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./backend:/app