// frontend/src/types/source.types.ts

export type FetchType = "Pull" | "Push";

export type SourceStatus = "connected" | "pending" | "disconnected";

export interface SourceInstance {
  id: string;
  product: string;
  vendor: string;
  fetchType: FetchType;
  description: string;
  active: boolean;
  // Pull only
  apiUrl?: string;
  apiToken?: string;
  // Push only (generated by system)
  pushEndpoint?: string;
  pushToken?: string;
  // Status
  status: SourceStatus;
  createdAt: string;
  updatedAt: string;
}
