// src/utils/countryUtils.ts
export function guessCountryCode(name: string): string {
    const n = (name || "").toLowerCase().trim();
    const map: Record<string, string> = {
      "brazil": "BR",
      "united states": "US",
      "usa": "US",
      "canada": "CA",
      "netherlands": "NL",
      "germany": "DE",
      "france": "FR",
      "italy": "IT",
      "spain": "ES",
      "portugal": "PT",
      "united kingdom": "GB",
      "uk": "GB",
      "argentina": "AR",
      "chile": "CL",
      "colombia": "CO",
      "peru": "PE",
      "mexico": "MX",
      "uruguay": "UY",
      "paraguay": "PY",
      "bolivia": "BO",
      "venezuela": "VE",
      "india": "IN",
      "china": "CN",
      "japan": "JP",
      "russia": "RU",
      "russian federation": "RU",
      "south africa": "ZA",
      "australia": "AU",
      "bulgaria": "BG",
      "singapore": "SG",
      "hong kong": "HK",
      "thailand": "TH",
      "kingdom of thailand": "TH",
      "poland": "PL",
      "republic of poland": "PL",
      "republic of korea": "KR",
      "korea, republic of": "KR",
    };
    return map[n] || "";
  }
  